<?php
namespace App\Controllers\Auth;

use App\Models\LoginAttemptModel;
use Ramsey\Uuid\Uuid;

class Login extends BaseController
{
    public function index()
    {
        // Load the users model and check if there are any users in the database, if not, redirect to the registration page
        $model = model('UserModel');
        if ($model->countAllResults() == 0) {
            return redirect()->to('/auth/register');
        }

        // Do garbage collection to clean up old password reset requests
        $model = model('PasswordResetModel');
        // Delete password reset requests older than 1 hour
        $model->where('created_at <', date('Y-m-d H:i:s', strtotime('-1 hour')))->delete();

        // Test if user is already logged in
        if ($this->session->get('user_uuid')) {
            return redirect()->to(site_url());
        }

        // Get referrer URL
        $redirect = $this->request->getGet('redirect');
        if($redirect === null) {
            $redirect = site_url();
        }

        // Set referrer URL in session
        $this->session->set('redirect', $redirect);

        $data['js'] = ['auth/login'];
        $data['title'] = 'Login';
        $data['templateMaxWidth'] = '330px';
        return view('auth/login', $data);
    }

    public function process()
    {
        $ip = $this->request->getIPAddress();
        $attemptModel = new LoginAttemptModel();
        if ($attemptModel->isBlocked($ip)) {
            return $this->response->setStatusCode(429)->setJSON(['error' => 'Too many failed login attempts. Please try again later.']);
        }

        // Capture JSON data
        $data = $this->request->getJSON(true);
        $email = $data['email'] ?? null;
        $password = $data['password'] ?? null;
        $remember = $data['remember'] ?? null;
        $csrf_token = $data[csrf_token()] ?? null;
        // Validate CSRF token
        if (!hash_equals(csrf_hash(), $csrf_token)) {
            return $this->response->setStatusCode(403)->setJSON(['error' => 'Invalid CSRF token']);
        }
        // Validate email and password
        if (empty($email) || empty($password)) {
            return $this->response->setStatusCode(400)->setJSON(['error' => 'Email and password are required']);
        }
        // Load user model and attempt to log in
        $model = model('UserModel');
        $user = $model->where('email', $email)
                ->where('validated', 1) // Ensure the user has validated their email address
                ->where('banned', 0) // Ensure the user is not banned
                ->first();
        if (!$user || !password_verify($password, $user['password'])) {
            $attemptModel->record($ip, $email);
            logit("Failed login attempt for: {$email}", 1); // Log to database with WARNING level
            return $this->response->setStatusCode(401)->setJSON(['error' => 'Invalid email or password']);
        }

        // Load the group model and get the user's groups
        $model = model('GroupModel');
        $groups = $model->where('user_uuid', $user['uuid'])->findColumn('group');

        // Set cookie expiration based on "remember me" option
        $cookieTimeout = $remember ? time() + (86400 * 365) : 0; // 1 year if remember me is checked, otherwise session cookie

        // Set cookies that can be read across all subdomains and set to expire in 1 year
        setcookie('user_uuid', $user['uuid'], $cookieTimeout, '/');
        setcookie('username', $user['username'], $cookieTimeout, '/');
        setcookie('email', $user['email'], $cookieTimeout, '/');

        // Generate a uuid for the apikey and save it in the database, this will be used for API authentication
        $apikey = Uuid::uuid4()->toString();
        $model = model('ApikeyModel');
        $model->insert([
            'user_id' => $user['id'],
            'uuid' => Uuid::uuid4()->toString(),
            'user_uuid' => $user['uuid'],
            'key' => $apikey,
            // If administrators group is in the user's groups, set the API key as an admin key
            'is_admin' => in_array('administrators', $groups) ? 1 : 0,
            'email' => $user['email'],
            'autogenerated' => 1,
            'note' => 'API key generated on login for user session',
        ]);

        // Set cookie for API key
        setcookie('apikey', $apikey, $cookieTimeout, '/');

        // Set session data
        $this->session->set('user_uuid', $user['uuid']);
        $this->session->set('apikey', $apikey);
        $this->session->set('email', $user['email']);
        $this->session->set('user_id', $user['id']);
        $this->session->set('username', $user['username']);
        $this->session->set('realname', $user['realname']);
        $this->session->set('groups', $groups);
        $this->session->set('is_admin', in_array('administrators', $groups));

        // Set redirect URL from session or default to main site
        $redirect = $this->session->get('redirect') ?? site_url();

        $attemptModel->clearForIp($ip);
        logit("User logged in: {$user['email']} ({$user['username']})", 0); // Log to database with INFO level

        // Return success response with redirect URL
        return $this->response->setStatusCode(200)->setJSON(['success' => true, 'redirect' => $redirect]);
    }
}