<?php

namespace App\Filters;

use CodeIgniter\Filters\FilterInterface;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;

class AuthFilter implements FilterInterface
{
    public function before(RequestInterface $request, $arguments = null)
    {
        $session = session();

        if ($session->get('user_uuid')) {
            if (!$session->get('is_admin')) {
                return redirect()->to('/unauthorised');
            }
            return;
        }

        $apikey = $_COOKIE['apikey'] ?? null;
        if (!$apikey) {
            return redirect()->to('/auth?redirect=' . urlencode(current_url()));
        }

        $apikeyModel = model('ApikeyModel');
        $keyRecord = $apikeyModel->where('key', $apikey)->where('autogenerated', 1)->first();
        if (!$keyRecord) {
            return redirect()->to('/auth?redirect=' . urlencode(current_url()));
        }

        $userModel = model('UserModel');
        $user = $userModel->where('uuid', $keyRecord['user_uuid'])
            ->where('validated', 1)
            ->where('banned', 0)
            ->first();
        if (!$user) {
            return redirect()->to('/auth?redirect=' . urlencode(current_url()));
        }

        $groupModel = model('GroupModel');
        $groups = $groupModel->where('user_uuid', $user['uuid'])->findColumn('group');

        $session->set('user_uuid',  $user['uuid']);
        $session->set('apikey',     $apikey);
        $session->set('email',      $user['email']);
        $session->set('user_id',    $user['id']);
        $session->set('username',   $user['username']);
        $session->set('realname',   $user['realname']);
        $session->set('groups',     $groups);
        $session->set('is_admin',   in_array('administrators', $groups));

        if (!$session->get('is_admin')) {
            return redirect()->to('/unauthorised');
        }
    }

    public function after(RequestInterface $request, ResponseInterface $response, $arguments = null)
    {
    }
}
