<?php

namespace App\Filters;

use CodeIgniter\Filters\FilterInterface;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;

class SessionFilter implements FilterInterface
{
    public function before(RequestInterface $request, $arguments = null)
    {
        $session = session();

        // Session already hydrated — nothing to do.
        if ($session->get('user_uuid')) {
            return;
        }

        // No API key cookie present — visitor is unauthenticated; leave the session empty.
        $apikey = $_COOKIE['apikey'] ?? null;
        if (!$apikey) {
            return;
        }

        // Validate the cookie value against an auto-generated key in the database.
        $apikeyModel = model('ApikeyModel');
        $keyRecord = $apikeyModel->where('key', $apikey)->where('autogenerated', 1)->first();
        if (!$keyRecord) {
            return;
        }

        // Confirm the associated user is active (validated and not banned).
        $userModel = model('UserModel');
        $user = $userModel->where('uuid', $keyRecord['user_uuid'])
            ->where('validated', 1)
            ->where('banned', 0)
            ->first();
        if (!$user) {
            return;
        }

        // Hydrate the session with user identity and group membership.
        $groupModel = model('GroupModel');
        $groups = $groupModel->where('user_uuid', $user['uuid'])->findColumn('group');

        $session->set('user_uuid',  $user['uuid']);
        $session->set('apikey',     $apikey);
        $session->set('email',      $user['email']);
        $session->set('user_id',    $user['id']);
        $session->set('username',   $user['username']);
        $session->set('realname',   $user['realname']);
        $session->set('groups',     $groups);
        $session->set('is_admin',   in_array('administrators', $groups));
    }

    public function after(RequestInterface $request, ResponseInterface $response, $arguments = null)
    {
    }
}
