<?php

namespace App\Controllers\Auth\Admin;

use App\Models\ApikeyModel;
use App\Models\UserModel;
use Ramsey\Uuid\Uuid;

class ApiKeys extends BaseController
{
    public function index()
    {
        $data['title']           = 'Auth Admin API Keys';
        $data['js']              = ['auth/admin/apikeys'];
        $data['templateMaxWidth'] = '96%';
        $data['templateMenu']    = 'auth/admin/sidebar-menu';
        return view('auth/admin/apikeys', $data);
    }

    public function getData()
    {
        $model = new ApikeyModel();

        $page    = max(1, (int)($this->request->getGet('page') ?? 1));
        $perPage = in_array((int)($this->request->getGet('per_page') ?? 20), [10, 20, 50, 100])
                   ? (int)$this->request->getGet('per_page')
                   : 20;
        $search  = trim((string)($this->request->getGet('search') ?? ''));
        $sortCol = $this->request->getGet('sort') ?? 'id';
        $sortDir = strtolower((string)($this->request->getGet('dir') ?? 'asc')) === 'desc' ? 'DESC' : 'ASC';

        $allowed = ['id', 'email', 'is_admin', 'autogenerated', 'created_at'];
        if (!in_array($sortCol, $allowed)) {
            $sortCol = 'id';
        }

        if ($search !== '') {
            $model->groupStart()
                  ->like('email', $search)
                  ->orLike('note', $search)
                  ->orLike('key', $search)
                  ->groupEnd();
        }

        $total  = $model->countAllResults(false);
        $offset = ($page - 1) * $perPage;

        $keys = $model->select('id, uuid, user_id, email, key, is_admin, autogenerated, note, created_at')
                      ->orderBy($sortCol, $sortDir)
                      ->findAll($perPage, $offset);

        return $this->response->setJSON([
            'total'    => $total,
            'page'     => $page,
            'per_page' => $perPage,
            'pages'    => $total > 0 ? (int)ceil($total / $perPage) : 0,
            'keys'     => $keys,
        ]);
    }

    public function getApikey($id)
    {
        $model  = new ApikeyModel();
        $apikey = $model->select('id, uuid, user_id, user_uuid, email, key, is_admin, autogenerated, note, created_at')
                        ->find((int)$id);

        if (!$apikey) {
            return $this->response->setStatusCode(404)->setJSON(['error' => 'API key not found.']);
        }

        return $this->response->setJSON($apikey);
    }

    public function createApikey()
    {
        $email    = trim((string)($this->request->getPost('email') ?? ''));
        $isAdmin  = (int)(bool)$this->request->getPost('is_admin');
        $note     = trim((string)($this->request->getPost('note') ?? ''));

        if ($email === '') {
            return $this->response->setStatusCode(400)->setJSON(['error' => 'Email is required.']);
        }

        $userModel = new UserModel();
        $user      = $userModel->where('email', $email)->first();
        if (!$user) {
            return $this->response->setStatusCode(404)->setJSON(['error' => 'No user found with that email address.']);
        }

        $model = new ApikeyModel();

        $model->insert([
            'user_id'       => $user['id'],
            'uuid'          => Uuid::uuid4()->toString(),
            'user_uuid'     => $user['uuid'],
            'key'           => bin2hex(random_bytes(32)),
            'email'         => $email,
            'is_admin'      => $isAdmin,
            'autogenerated' => 0,
            'note'          => $note,
        ]);

        logit("Admin created API key for user {$user['id']} ({$email}).");

        return $this->response->setJSON(['success' => true]);
    }

    public function updateApikey($id)
    {
        $model = new ApikeyModel();
        $id    = (int)$id;

        if (!$model->find($id)) {
            return $this->response->setStatusCode(404)->setJSON(['error' => 'API key not found.']);
        }

        $email = trim((string)($this->request->getPost('email') ?? ''));
        if ($email === '') {
            return $this->response->setStatusCode(400)->setJSON(['error' => 'Email is required.']);
        }

        $userModel = new UserModel();
        $user      = $userModel->where('email', $email)->first();
        if (!$user) {
            return $this->response->setStatusCode(404)->setJSON(['error' => 'No user found with that email address.']);
        }

        $model->update($id, [
            'user_id'   => $user['id'],
            'user_uuid' => $user['uuid'],
            'email'     => $email,
            'is_admin'  => (int)(bool)$this->request->getPost('is_admin'),
            'note'      => trim((string)($this->request->getPost('note') ?? '')),
        ]);

        logit("Admin updated API key ID {$id} ({$email}).");

        return $this->response->setJSON(['success' => true]);
    }

    public function deleteApikey($id)
    {
        $model = new ApikeyModel();
        $id    = (int)$id;

        $apikey = $model->select('id, email')->find($id);
        if (!$apikey) {
            return $this->response->setStatusCode(404)->setJSON(['error' => 'API key not found.']);
        }

        $model->delete($id);

        logit("Admin deleted API key ID {$id} ({$apikey['email']}).", 1);

        return $this->response->setJSON(['success' => true]);
    }

    public function bulkDelete()
    {
        $ids = $this->request->getPost('ids');

        if (!is_array($ids) || empty($ids)) {
            return $this->response->setStatusCode(400)->setJSON(['error' => 'No IDs provided.']);
        }

        $ids = array_filter(array_map('intval', $ids));

        if (empty($ids)) {
            return $this->response->setStatusCode(400)->setJSON(['error' => 'No valid IDs provided.']);
        }

        $model = new ApikeyModel();
        $model->delete($ids);

        logit('Admin bulk deleted ' . count($ids) . ' API key(s): IDs ' . implode(', ', $ids) . '.', 1);

        return $this->response->setJSON(['success' => true, 'deleted' => count($ids)]);
    }
}
